### ISSUE TITLE
wrong testnet URL in Docs

### ISSUE THREAD

**Issue by robertopca** [maticnetwork/matic-docs#1122]
In the documentation, the rpc url is:
https://rpc-mumbai.matic.today/
but if you try to connect to metamask it does not work.
in a forum i found this is the correct rpc url for mumbai network: 
https://matic-mumbai.chainstacklabs.com/
if that is ok, please update the docs.

**Comment by ashucoder9** [comment]
Hey @robertopca, thanks for the update. We are looking into this and will update with the correct RPC asap.

**Comment by ashucoder9** [comment]
This is fixed.
