### ISSUE TITLE
docs need update for new directory structure in heimdall image v0.3.0

### ISSUE THREAD

**Issue by thorstenhirsch** [maticnetwork/matic-docs#1258]
While trying to run a heimdall v0.3 container according to docs/develop/network-details/full-node-docker.md I've noticed that the directory structure has changed, e.g.:

heimdalld is now in /usr/bin instead of /usr/local/bin
$HOME is now /var/lib/heimdall instead of /heimdall-home

The new init command in the docs needs to be updated to `docker run -v /mnt/data/heimdall:/var/lib/heimdall:rw --entrypoint /usr/bin/heimdalld -it 0xpolygon/heimdall:0.3.0 init --home=/var/lib/heimdall`.

**Comment by thorstenhirsch** [comment]
...or is it too early? I get `Stopping peer for error` errors with `err=EOF` when starting my heimdall v0.3.0 node. Does the latest version only work with mumbai right now?

**Comment by ashucoder9** [comment]
I believe the changes are live @thorstenhirsch.
