### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by fallanic** [maticnetwork/matic-docs#1306]
Hi there 👋 

The demo on https://wiki.polygon.technology/docs/develop/ethereum-polygon/tools/widget/ is a dead link https://github.com/maticnetwork/wallet-widget-example

The GitHub URL of the npm module (https://www.npmjs.com/package/@maticnetwork/wallet-widget) also is a dead link https://github.com/maticnetwork/wallet-widget

At first I thought maybe these are deprecated, but the wiki page has been updated today (Jan 12th 2023) and the npm module last published 2 months ago.

Just wanted to let you know, thanks :)

**Comment by ashucoder9** [comment]
Thanks for pointing it out. That's actually a deprecated page and we no longer provide regular updates for the service on Wiki.

**Comment by fallanic** [comment]
Sounds good, it might be worth mentioning at the top of the page that it is deprecated.
