### ISSUE TITLE
Liveness of IBFT 2.0

### ISSUE THREAD

**Issue by cryptohazard** [maticnetwork/matic-docs#1590]
Hey guys, I was just reading about [Network Benefits](https://github.com/maticnetwork/matic-docs/blob/master/docs/supernets/design/consensus/polybft/ibft.md#network-benefits) in your doc. My question is this bit : 
>It has been proven that IBFT 2.0 does not guarantee BFT persistence nor liveness when operating on a synchronous network.

Is it **sync** or **async**? From reading the following sentence I feel like it should be **asynchronous network** but maybe I still don't understand everything.
For reference, I found your doc while looking into IBFT.
cheers

**Comment by ashucoder9** [comment]
@DannyS03

**Comment by Ishmaello** [comment]
RPC endpoint if included as I quoted if I'm right, how to complete that section when mumbai RPC already created, next step?
