### ISSUE TITLE
19 days pending 

### ISSUE THREAD

**Issue by michelsaad** [maticnetwork/matic-docs#1596]
19 days pending 
![Screenshot 2023-04-13 024537](https://user-images.githubusercontent.com/58457059/231619950-34322aaf-3262-4c52-a25f-04f892316292.png)

**Comment by ashucoder9** [comment]
Hey @michelsaad, what's the issue with the docs that you are trying to point out?

**Comment by DannyS03** [comment]
Closing due to general transaction query and not docs-related. Please reopen if otherwise.
