### ISSUE TITLE
Lightpaper pdf link not working

### ISSUE THREAD

**Issue by criadoperez** [maticnetwork/matic-docs#1747]
The link configured [here](https://github.com/maticnetwork/matic-docs/blob/master/docusaurus.config.js#L184-L187) to Polygon's lightpaper is not valid.

https://polygon.technology/lightpaper-polygon.pdf

Is the pdf available somewhere else or its best to remove it?

**Comment by ashucoder9** [comment]
It has been recently removed to possibly produce a new document that summarizes the Polygon 2.0 stack.

We'll update the link once that happens. Thank you for your patience 🙏🏽

**Comment by DannyS03** [comment]
@ashucoder9 let's remove in the meantime.

**Comment by criadoperez** [comment]
> @ashucoder9 let's remove in the meantime.

I provided a PR with the link commented out until a working one is provided.
