### ISSUE TITLE
Unable to get the result of bridging an erc20 token from Mainnet->Matic

### ISSUE THREAD

**Issue by JasoonS** [maticnetwork/matic-docs#307]
When I try run this websocket query I don't get the correct result.

https://github.com/maticnetwork/matic-docs/blob/2a284242f11b17957789b318c6f4c8844036a9c9/docs/develop/ethereum-matic/pos/deposit-withdraw-event-pos.md#L37

When I use `"wss://ws-mumbai.matic.today/"` I get the following error:
```
{"jsonrpc":"2.0","id":null,"error":{"code":-32700,"message":"invalid character 'x' after object key:value pair"}}
```

When I use Matic Vigil: "wss://rpc-mainnet.maticvigil.com/ws/v1/<my-api-key" the websocket connection closes automatically and I get no result.

**Comment by JasoonS** [comment]
Also worth mentioning that to get this to work in the browser I needed to change `ws.on` to `ws.addEventListener`.

**Comment by itzmeanjan** [comment]
> When I try run this websocket query I don't get the correct result.
> 
> https://github.com/maticnetwork/matic-docs/blob/2a284242f11b17957789b318c6f4c8844036a9c9/docs/develop/ethereum-matic/pos/deposit-withdraw-event-pos.md#L37
> 
> When I use `"wss://ws-mumbai.matic.today/"` I get the following error:
> 
> ```
> {"jsonrpc":"2.0","id":null,"error":{"code":-32700,"message":"invalid character 'x' after object key:value pair"}}
> ```

Hello @JasoonS , let me know what did you use in place of `childChainManagerProxy` ? 



> Also worth mentioning that to get this to work in the browser I needed to change `ws.on` to `ws.addEventListener`.

Yes correct, example was written considering it's being run in NodeJS console application.

**Comment by JasoonS** [comment]
I've tried with the `childChainManagerProxy` as both "0xb5505a6d998549090530911180f38aC5130101c6" and "0xA6FA4fB5f76172d178d61B04b0ecd319C5d1C0aa". I get the same result.

I will try the method here, and just poll for that value. https://github.com/maticnetwork/matic-docs/blob/2a284242f11b17957789b318c6f4c8844036a9c9/docs/develop/ethereum-matic/pos/deposit-withdraw-event-pos.md#historical-deposit-completion-check-by-querying-the-blockchain

**Comment by itzmeanjan** [comment]
Consider polling as of now.
