### ISSUE TITLE
Request to add docs to run a basic listener node / non-validator node

### ISSUE THREAD

**Issue by zemse** [maticnetwork/matic-docs#391]
I couldn't find documentation for running a non-validator node that only receives the latest blocks.

Places where I looked:
- https://docs.matic.network
- https://www.notion.so/Matic-Mainnet-71ff5825eef1455f8c27884f1db649ab

Most of the tutorials available are based on Ansible playbooks, which spins up a validator full node. I've tried to go through the [setup scripts](https://github.com/maticnetwork/launch/tree/master/mainnet-v1/without-sentry) but really struggling to set up a pruned / light client. Any help would be very much appreciated.

**Comment by hdiass** [comment]
Following this issue very closely. Seeking the same.

**Comment by delroybosco** [comment]
Please follow this documentation: https://docs.matic.network/docs/integrate/full-node-deployment/
