### ISSUE TITLE
Description of Execution layer is incorrect

### ISSUE THREAD

**Issue by rkapka** [maticnetwork/matic-docs#473]
On https://polygon.technology/technology/, when describing architecture, the description of Execution layer says:
> Security layer is fully abstract and can have multiple instances, implemented by different entities and with different characteristics. It can also be implemented directly on Ethereum, in which case the Ethereum miners perform the validation.

This is a copy/paste from the Security layer and should not be a part of the Execution layer.

**Comment by jeffersonnnn** [comment]
Thank you for catching this! We've updated the copy on the page and it reflects the true description of the Execution layer.
