### ISSUE TITLE
Clarify Plasma exit mechanism

### ISSUE THREAD

**Issue by Neozaru** [maticnetwork/matic-docs#483]
**Problem:**
- Plasma withdrawal from Matic to Ethereum mainnet represents an UX challenge. The constraint is technical, thus documentation needs to be clearer about what the user needs to do and how to do it.
For context,
(a) I have initiated a MATIC token withdrawal from Polygon to Ethereum. I have waited 7 days only to find out that I needed to perform a mainnet tx to start the 7 days counter (but I could not perform that tx before the next checkpoint after I initiated, which was not crystal-clear to me). This is very inconvenient for me and could be solved simply with better information. I am happy to edit the page if you have the link to the corresponding file on Github or other.
(b) It is very hard to initiate the withdrawal now because the account is a Ledger + Metamask one, with lots of fields to validate. Actually there are so many that I didn't make it to the end of the process (there are at least 40). It would be reassuring if the doc could warn the user before-hand, because the constraints of physical devices can make us sign things that we can't realistically validate (hex strings, hex strings everywhere) - which is how some scams operate.

**Proposed solution:**

Updating withdrawal instructions is some pages such as https://docs.matic.network/docs/develop/ethereum-matic/plasma/eth
- Stress the fact that there are X active txs to make, at different timings, and that it's not a "initiate then come back in 7 days" type of thing.
- Maybe some technical info about doing that with physical devices such as ledger - unless we consider that the issue is very ledger-specific and shouldn't be addressed as part of this.

I am happy to help editing the docs if you agree with the general idea.

**Comment by anurag-arjun** [comment]
Agreed - the instructions can be made clearer.

It would be great if you can edit the doc! Here's the link - https://github.com/maticnetwork/matic-docs/blob/master/docs/develop/ethereum-matic/plasma/eth.md

@Neozaru

**Comment by anurag-arjun** [comment]
Please feel free to submit a PR.
