### ISSUE TITLE
Matic rpc url in Metamask help file is wrong

### ISSUE THREAD

**Issue by staticpo** [maticnetwork/matic-docs#593]
In this file: https://github.com/maticnetwork/matic-docs/blob/master/docs/develop/metamask/config-polygon-on-metamask.md

The rpc url recomended for metamask is `https://rpc-mumbai.maticvigil.com/` while now the recommended one is: `https://polygon-rpc.com/`, as per [https://docs.matic.network/docs/develop/network-details/network/](https://docs.matic.network/docs/develop/network-details/network/)

**Comment by jeffersonnnn** [comment]
Both are perfectly fine. https://rpc-mumbai.maticvigil.com/ is our internal tool while https://polygon-rpc.com/ is something of a "load balancer" created by members of our amazing community.
