### ISSUE TITLE
Change Fortmatic settings example to use their default nodes

### ISSUE THREAD

**Issue by alinkedd** [maticnetwork/matic-docs#601]
Got into the issue, that [Fortmatic RPC url](https://docs.polygon.technology/docs/develop/wallets/fortmatic) should be changed according to their [explanation about Matic nodes](https://docs.fortmatic.com/web3-integration/network-configuration#switch-network-to-custom-node), while usage of `https://rpc-mumbai.matic.today` url leads to CORS problem on Fortmatic side and it seems that usage of custom nodes should be approved by support.

**Comment by jeffersonnnn** [comment]
This has been handled. Thank you for catching this!
