### ISSUE TITLE
"Edit this page" on docs.polygon.technology points to master branch when it should point to polygon branch

### ISSUE THREAD

**Issue by timjrobinson** [maticnetwork/matic-docs#646]
When clicking the "Edit this page" link on say https://docs.polygon.technology/docs/faq/wallet-bridge-faq/ It takes you to this repository but with master branch selected, which has different code to the doc you were just looking at. 

That link should take users to the polygon branch instead so it's easy to edit and submit updates to the docs.

**Comment by vidyaakrishna** [comment]
Thanks, updated the master branch with the right code.
