### ISSUE TITLE
links direct to homepage

### ISSUE THREAD

**Issue by ph4ni** [maticnetwork/matic-docs#660]
> Steps to use the PoS Bridge#
>
>Before we enter into this section of the docs, it may help to have a thorough understanding of these terms as you'll interact with them while trying to use the bridge. Mapping and the State Sync Mechanism 

the "mapping" and "state sync mechanism" links are not working

[https://docs.polygon.technology/docs/develop/ethereum-polygon/pos/getting-started](https://docs.polygon.technology/docs/develop/ethereum-polygon/pos/getting-started)

**Comment by vidyaakrishna** [comment]
Thanks, this has been updated.

**Comment by ph4ni** [comment]
perfect!
