### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by vmohan7** [maticnetwork/matic-docs#666]
On this guide[ Mapping Assets ](https://docs.polygon.technology/docs/develop/ethereum-polygon/pos/mapping-assets) guide, the link to the mintable assets guide is broken. The first link should point here instead ; https://docs.polygon.technology/docs/develop/ethereum-polygon/mintable-assets

**Comment by vidyaakrishna** [comment]
Thanks, this is fixed.
