### ISSUE TITLE
Add: A single Page having all the details of Metamask  with steps!

### ISSUE THREAD

**Issue by Uttam-Singhh** [maticnetwork/matic-docs#708]
Right now in docs, there is no single page with all the information from How to install Metamaks to How to configure it!

For example, we have - 
https://docs.polygon.technology/docs/develop/metamask/hello 
`or` 
https://docs.polygon.technology/docs/develop/metamask/custom-tokens

But we don't have - https://docs.polygon.technology/docs/develop/metamask

So it would be great if we can Add a Page with all the steps that one needs to follow to set up Metamask!

The Page can have Bullet point containing links to our current docs something like this -

## Metamask for Polygon

* How to create a MetaMask Wallet?
* Configure Polygon on Metamask
* Config Custom Tokens
* Multiple Accounts

This thing will be helpful in creating future Docs as well since one can provide a link to this page `Set up a Development Test Wallet` whenever there is a discussion of Metamask.

**Comment by Nazeim** [comment]
@Uttam-Singhh 
You can create an "Overview" article within the "Metamask" section, where you can create a few sentences about Metamask and then add the list of useful links that you mentioned.

**Comment by Uttam-Singhh** [comment]
@Nazeim Please review the PR!

**Comment by romain130492** [comment]
alright... I was wondering why polygon doc was wrong about metamask... 
There is no info @Uttam-Singhh about getting the user's metamask wallet on a mobile, [your doc](https://docs.polygon.technology/docs/develop/wallets/metamask) shows the use of `window.ethereum`, which well doesn't exist on mobile browsers.
;)

**Comment by Uttam-Singhh** [comment]
Hello @romain130492,
Thanks for pointing it out, will have a look & get back to you!
