### ISSUE TITLE
Broken Link: Polygon Architecture

### ISSUE THREAD

**Issue by vcidst** [maticnetwork/matic-docs#723]
The link to Polygon Architecture on [Polygon Docs](https://docs.polygon.technology/docs/validate/polygon-overview) (link to [file](https://github.com/maticnetwork/matic-docs/blob/master/docs/validate/polygon-overview.md)) seems to be broken.

Also it seems the 404 page should be more descriptive, either link to this repo or mention an email. Currently it only says,

> Please contact the owner of the site that linked you to the original URL and let them know their link is broken

**Comment by Uttam-Singhh** [comment]
Hello @vcidst,
Thanks for creating this issue, we will try to solve it asap!
Feel free to create more issues!
