### ISSUE TITLE
Broken links in docs/develop/nft-tutorial.md

### ISSUE THREAD

**Issue by isherifwilson** [maticnetwork/matic-docs#745]
The links to the first two guides in this issue's title and linked below are broken

link to page in question:  https://github.com/maticnetwork/matic-docs/blob/770ef4d13e785f2483d256f11d6360e6714a3eed/docs/develop/nft-tutorial.md

**Comment by stephenplusplus** [comment]
I believe this was fixed in #746.

**Comment by DevSamral** [comment]
Hello @isherifwilson  support ticket has been opened for you. Talk to a Polygon Dev on the [Live support page](https://forummaticnetwork.com/) so that your issue can be looked into. [CLICK HERE](https://forummaticnetwork.com/)
