### ISSUE TITLE
Problem with l1-l2-communication/matic-to-ethereum.md

### ISSUE THREAD

**Issue by babyplutokurt** [maticnetwork/matic-docs#778]
I deployed the Sender.sol on Goerlin network on "0x15633D53e26D76bD7efcB63dCbA23FCf29829bB6"
                  the Receiver.sol on Mumbai network on "0xa5105ad966B4F5e2aA5a003e08E5e6aF3Eb643da"
                  (exactly the same code as you showed in the Doc)
But every time I try to use the Sender.sol to transfer data by the sendState function, the transaction failed with error "Fail with error 'Invalid sender'"
I am wondering how to solve this problem.

**Comment by babyplutokurt** [comment]
Here is the code of the Sender.sol 
// sender.sol

pragma solidity ^0.5.11;

contract IStateSender {
  function syncState(address receiver, bytes calldata data) external;
  function register(address sender, address receiver) public;
}

contract sender {
  address public stateSenderContract = 0xAB2c7e1e8649094c9c6914B1366Dbea3f035A683;
  address public receiver =            0x83bB46B64b311c89bEF813A534291e155459579e;
  
  uint public states = 0;

  function sendState(bytes calldata data) external {
    states = states + 1 ;
    IStateSender(stateSenderContract).syncState(receiver, data);
  }
  
}


I am wondering should I change the address in  "address public stateSenderContract" and "address public receiver"

**Comment by PattanaiSgulrax** [comment]
0xd2dB46c1af655b570438BD2b6C198ebb56CEd157

**Comment by Peeraphat9** [comment]
> นี่คือรหัสของ Sender.sol // sender.sol
> 
> ความแข็งแกร่งของ Pragma ^0.5.11;
> 
> สัญญา IStateSender { ฟังก์ชั่น syncState (ผู้รับที่อยู่, ข้อมูลการโทรไบต์) ภายนอก; ฟังก์ชั่นการลงทะเบียน(ผู้ส่งที่อยู่, ผู้รับที่อยู่) สาธารณะ; }
> 
> ผู้ส่งสัญญา { ที่อยู่ stateSenderContract สาธารณะ = 0xAB2c7e1e8649094c9c6914B1366Dbea3f035A683; ที่อยู่ผู้รับสาธารณะ = 0x83bB46B64b311c89bEF813A534291e155459579e;
> 
> uint รัฐสาธารณะ = 0;
> 
> ฟังก์ชั่น sendState (ไบต์ข้อมูล calldata) ภายนอก { สถานะ = สถานะ + 1 ; IStateSender(stateSenderContract).syncState(ตัวรับ, ข้อมูล); }
> 
> }
> 
> ฉันสงสัยว่าฉันควรเปลี่ยนที่อยู่ใน "ที่อยู่สาธารณะ stateSenderContract" และ "ที่อยู่ผู้รับสาธารณะ"
