### ISSUE TITLE
_fxERC20Token in FxERC20RootTunnel constructor

### ISSUE THREAD

**Issue by voyager-gold** [maticnetwork/matic-docs#846]
Anybody please help what _fxERC20Token is in constructor.

https://docs.polygon.technology/docs/develop/l1-l2-communication/fx-portal#fxerc20roottunnel
https://goerli.etherscan.io/address/0x3658ccFDE5e9629b0805EB06AaCFc42416850961#code#F1#L25

**Comment by QEDK** [comment]
> Anybody please help what _fxERC20Token is in constructor.
> 
> https://docs.polygon.technology/docs/develop/l1-l2-communication/fx-portal#fxerc20roottunnel https://goerli.etherscan.io/address/0x3658ccFDE5e9629b0805EB06AaCFc42416850961#code#F1#L25

It's supposed to be a child token contract template on Polygon either same as FxERC20 or inheriting from it, you have to pass the address of any such deployed contract to both the tunnels.

**Comment by QEDK** [comment]
> @QEDK thanks. Can you please share the addresses of that token on both main & testnet? Also token template address of fxErc20ChildTunnel constructor as well.

They are available by querying the tunnels, currently https://polygonscan.com/address/0xad87e3b217c66b0d45deafbc540330d300811b94
