### ISSUE TITLE
trying deploy full node on google cloud but below errors 

### ISSUE THREAD

**Issue by gsngsn123** [maticnetwork/matic-docs#855]
Welcome to Cloud Shell! Type "help" to get started.
Your Cloud Platform project in this session is set to polygon-346517.
Use “gcloud config set project [PROJECT_ID]” to change to a different project.
ramesh_ram0341@cloudshell:~ (polygon-346517)$    export POLYGON_NETWORK=mainnet
   export POLYGON_NODETYPE=fullnode
   export POLYGON_BOOTSTRAP_MODE=snapshot
   export POLYGON_RPC_PORT=8747
   export GCP_NETWORK_TAG=polygon
   export EXTRA_VAR="bor_branch=v0.2.14 heimdall_branch=v0.2.8  network_version=mainnet-v1 node_type=sentry/sentry heimdall_network=${POLYGON_NETWORK}" 
   gcloud compute firewall-rules create "polygon-p2p" --allow=tcp:26656,tcp:30303,udp:30303 --description="polygon p2p" --target-tags=${GCP_NETWORK_TAG}
   gcloud compute firewall-rules create "polygon-rpc" --allow=tcp:${POLYGON_RPC_PORT} --description="polygon rpc" --target-tags=${GCP_NETWORK_TAG}
   export INSTANCE_NAME=polygon-0
   export INSTANCE_TYPE=e2-standard-8
   export BOR_EXT_DISK_SIZE=1024
{POLYGON_NETWORK}' -m '${POLYGON_NODETYPE}' -s '${POLYGON_BOOTSTRAP_MODE}' -p '${POLYGON_RPC_PORT}' -e \"'${EXTRA_VAR}'\"; bash"'.sh | bash -s -- -n '$
Creating firewall...failed.
ERROR: (gcloud.compute.firewall-rules.create) Could not fetch resource:
 - The resource 'projects/polygon-346517/global/firewalls/polygon-p2p' already exists

Creating firewall...failed.
ERROR: (gcloud.compute.firewall-rules.create) Could not fetch resource:
 - The resource 'projects/polygon-346517/global/firewalls/polygon-rpc' already exists

ERROR: (gcloud.compute.instances.create) unrecognized arguments:
  heimdall_branch=v0.2.8
  network_version=mainnet-v1 (did you mean '--network-tier'?)
  node_type=sentry/sentry
  heimdall_network=mainnet\"; bash"
  To search the help text of gcloud commands, run:
  gcloud help -- SEARCH_TERMS

**Comment by h4ckm1n-dev** [comment]
have the same error when trying to install polygon node on Gcloud

**Comment by fmhall** [comment]
The variable is getting more than one value, so you can store it in an array that should work. I just tested it and it worked for me.                                        
`export EXTRA_VAR=(bor_branch=v0.2.16 heimdall_branch=v0.2.9 network_version=mainnet-v1 node_type=sentry/sentry heimdall_network=${POLYGON_NETWORK})`

PR coming shortly
