### ISSUE TITLE
Contradictory statements about mapping with PoS and Plasma bridges

### ISSUE THREAD

**Issue by php4fan** [maticnetwork/matic-docs#868]
This guide:

https://docs.polygon.technology/docs/develop/ethereum-polygon/submit-mapping-request/

explains how to submit mapping requests and it seems to be possible to do that both for the POS and the Plasma bridges.

That is also linked from here: https://docs.polygon.technology/docs/develop/ethereum-polygon/mintable-assets/ (guide about Polygon Mintable Assets) where only the POS bridge is mentioned (as if polygon mintable assets are only possible through the POS bridge, although I haven't seen that stated explicitly).

However:
https://docs.polygon.technology/docs/develop/ethereum-polygon/plasma/mapping-assets
This seems to be a specific guide to mapping assets using the Plasma bridge, and it says:
> You can submit your mapping request here. Please make note that **this mapping submission form is for Plasma Bridge and for PoS bridge you have to directly contact the matic team on discord**.

That must be something that used to be true and no longer is, right?

**Comment by DannyS03** [comment]
Guides have been updated since, closing.
