### ISSUE TITLE
Explain how submitted mapping requests are handled (who reviews them, human beings???)

### ISSUE THREAD

**Issue by php4fan** [maticnetwork/matic-docs#869]
I have read the documentation that explains how assets are transferred between Polygon and Ethereum, how the bridges work, what is a mapping between contracts on both chains, the requirements that both contracts need to satisfy, and how to submit a request for the mapping to exist.

But I haven't found anything about how those submissions are handled. 
It almost sounds like requests are submitted to a team of human beings who review them, but that would be ridiculous. Or would it?

**Comment by DannyS03** [comment]
Guides have been updated since and further updates being made to reflect latest changes, closing.
