### ISSUE TITLE
Hello! other options beside Polygonscan?

### ISSUE THREAD

**Issue by TheFunkySkullsNFT** [maticnetwork/matic-docs#936]
I'm not sure where can I ask this question but I have a Smart Contract I need to verify, so i'm looking for something else beside Polygonscan??

my issue with Polygonscan is that to be able to verify a contract I have to create an account but every-time I try to open an account throws an error "Unable to create new user account." over and over again. not support page not info why. i'm using a strong password my email its a gmail the username is normal nothing weird. i solve the capcha.

**Comment by ashucoder9** [comment]
Hey @TheFunkySkullsNFT, please refer to this doc detailing prerequisites for Smart Contract Verification: https://docs.polygonscan.com/api-endpoints/contracts#verify-source-code
