### ISSUE TITLE
Explain how checkpoint snapshots can be used

### ISSUE THREAD

**Issue by garyrob** [maticnetwork/matic-docs#941]
At some point in the not-too-distant future, the Polygon PoS will be made pretty much obsolete by L2 technology such as Polygon's own Hermez, etc. At that point, development on the PoS will drastically slow and it may even become insecure due to having less value staked.

It would seem that the best solution for this would be for Polygon to provide bridges from the PoS to one or more high-profile L2s. And there is already a bridge between the PoS and Ethereum.

What isn't clear to me is whether, for example, ERC721 contracts which are created today on Polygon will be able to bridge tokens NFTs to an L2. It seems like Polygon Edge should enable this, but I haven't noticed an explicit statement that Polygon tokens created in contracts that exist now will, in the future, be able to be sent to one or more L2s via Edge. 

Right now, Edge is based on the concept of a Root and Child chains with Ethereum being the root. If the idea for getting an NFT off of PoS and onto an L2 in the future would use Ethereum L1 as an intermediary, that may be prohibitively expensive, as the future of low-fee transactions is on the L2s. Using L1 as an intermediary would defeat the main purpose of using the Polygon PoS in the first place, namely, low fees.

So, in order to increase the confidence of developers in investing in Polygon PoS development today, it would be helpful for the Polygon docs to make some statement about plans to enable low-fee bridging between PoS and one or more L2s in the future.

Even a statement here in this issue thread would be a good starting point! (Or, if I've missed something, I'd appreciate a link to it.)

**Comment by ashucoder9** [comment]
As of now, we do not have any update or statement from the team regarding this topic. I agree that it's in the best interest of community if we plan to enable low-fee bridging. Rest assured, if there is any update, we'll mention it explicitly on the Bridge docs.

Thanks @garyrob for your detailed explanation.
